databases:
  - name: BibliotecaEstrelaDB
    plan: free
    databaseName: biblioteca_estrela
    user: dbuser

services:
  - type: web
    plan: free
    name: BibliotecaEstrela
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn BibliotecaEstrela.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BibliotecaEstrelaDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4